#!/usr/bin/env python3

import sys
import random
import argparse

parser = argparse.ArgumentParser(description='Retrieve random selection of lines')
parser.add_argument('count', type=int, nargs='?', default=10)
count = parser.parse_args().count

result = []
for i, line in enumerate(sys.stdin):
    if len(result) < count:
        result.append(line)
    else:
        pos = random.randint(0, i)
        if pos < count:
            result[pos] = line

for line in result:
    print(line, end='')
